site_name: datachart
site_author: Erik Novak
site_description: >-
  Data visualization package, simple to use, highly customizable

repo_name: eriknovak/datachart
repo_url: https://github.com/eriknovak/datachart

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/imgs/logo.png
  favicon: assets/imgs/favicon.png

edit_uri: ""

plugins:
  - blog:
      blog_dir: how-to-guides
  - autorefs
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_root_toc_entry: False
            members_order: "source"
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_section_style: spacy
            heading_level: 3
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - Home: index.md

  - How-To Guides:
    - how-to-guides/index.md

  - Documentation:
    - Overview: documentation/overview.md
    - Charts:
      - Line Chart: documentation/notebooks/01-line-chart.ipynb
      - Bar Chart:  documentation/notebooks/02-bar-chart.ipynb
      - Histogram: documentation/notebooks/03-histogram.ipynb
      - Heatmap: documentation/notebooks/04-heatmap.ipynb
      - Color Themes: documentation/notebooks/00-color-themes.ipynb
    - Configuration: documentation/configuration.md

  - API Reference:
    - references/index.md
    - charts:
      - references/charts/index.md
    - utils:
      - references/utils/index.md
    - config:
      - references/config/index.md
    - themes:
      - references/themes/index.md
    - constants: references/constants.md
    - typings: references/typings.md


  - Changelog: changelog.md
  - Development: development.md
