site_name: datachart
site_author: Erik Novak
site_description: >-
  Data visualization package, simple to use, highly customizable

repo_name: eriknovak/datachart
repo_url: https://github.com/eriknovak/datachart

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/imgs/logo.png
  favicon: assets/imgs/favicon.png

edit_uri: ""

extra_css:
  - css/extra.css

plugins:
  - autorefs
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            members_order: "source"
            show_source: false
            show_labels: false
            show_root_heading: true
            show_root_toc_entry: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_signature_annotations: true
            separate_signature: true
            annotations_path: source
            docstring_section_style: spacy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - Home: index.md

  - How-To Guides:
    - how-to-guides/index.md
    - Charts:
      - how-to-guides/charts/index.md
      - Line Chart: how-to-guides/charts/linechart.ipynb
      - Bar Chart: how-to-guides/charts/barchart.ipynb
      - Histogram: how-to-guides/charts/histogram.ipynb
      - Heatmap: how-to-guides/charts/heatmap.ipynb
    - Utils:
      - how-to-guides/utils/index.md
    - Config: how-to-guides/config.md
    - Themes: how-to-guides/themes.ipynb
    - Colormaps: how-to-guides/colormaps.ipynb


  - API Reference:
    - references/index.md
    - charts:
      - references/charts/index.md
    - utils:
      - references/utils/index.md
      - stats: references/utils/stats.md
    - config:
      - references/config/index.md
    - themes:
      - references/themes/index.md
    - constants: references/constants.md
    - typings: references/typings.md


  - Changelog: changelog.md
  - Development: development.md
